project:
  name: Logistic Pack Facade
  debug: true
  environment: development

kafka:
  tick: 4s
  topics: 
    - "created"
    - "removed"
    - "updated"
  groupId: "logistic-pack"
  brokers:
    - "localhost:9094"
    # - "localhost:9095"
    # - "localhost:9096"
